
    
spring:
    datasource:
              url: jdbc:mysql://localhost:3306/springbbotymldb
              username: root
              password: root
              driver-class-name: com.mysql.jdbc.Driver
              
    jpa:
      properties:
        hibernate:
            dialect: org.hibernate.dialect.MySQL55Dialect 
      hibernate:
        ddl-auto: update
      show-sql: true
      
        



      
      